@echo off
cd /d C:\Projects\AOGChemModule\AOG-Plot-Manager\src\PlotManager
echo Scaffolding Avalonia app...
dotnet new avalonia.app -o PlotManager.Avalonia -n PlotManager.Avalonia -f net8.0
echo Adding to solution...
dotnet sln PlotManager.sln add PlotManager.Avalonia/PlotManager.Avalonia.csproj
echo Adding Core reference...
dotnet add PlotManager.Avalonia/PlotManager.Avalonia.csproj reference PlotManager.Core/PlotManager.Core.csproj
echo Adding packages...
dotnet add PlotManager.Avalonia/PlotManager.Avalonia.csproj package Mapsui.Avalonia
echo Done!
